### ISSUE TITLE
Price calculator supports 2CPU / 8GiB Machine Types

### ISSUE THREAD

**Issue by PK85** [kyma-project/price-calculator#38]
**Description**

In this story [Introduce 2 CPU / 8 GiB RAM machine types for aws, gcp, azure, ccee](https://github.com/kyma-project/kyma-environment-broker/issues/417) we have new smaller machine types available (which are default ones) and now we need adjust price calculator.

**Reasons**

Show smaller prices for customers in the price calculator.

**Comment by mrCherry97** [comment]
okay, I pushed the changes, @varbanv please review this PR: https://github.com/kyma-project/price-calculator/pull/39 and approve if values are okay
